export const COMPANY_DETAIL_SET = 'COMPANY_DETAIL_SET';
export const COMPANY_FAILURE = 'COMPANY_FAILURE';
export const COMPANY_REQUEST = 'COMPANY_REQUEST';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';

export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const TRADING_PARTNER_FAILURE = 'TRADING_PARTNER_FAILURE';
export const TRADING_PARTNER_REQUEST = 'TRADING_PARTNER_REQUEST';
export const TRADING_PARTNER_SUCCESS = 'TRADING_PARTNER_SUCCESS';
